# Configuration file template for rename_input_files
parameters:
    # Define the casename and output frequency to substitute in the file names and output directories
    # Define other parameters if needed
    # assign an anchor name using the `&`
    casename: &casename SAM0-UNICON
    frequency: &frequency mon

CASENAME: *casename
# Define the path to the directory containing the file(s) to rename
inputPath: /home/jessica.liptak/mdtf/inputdata/model/SAM0-UNICON_r1i1p1f1_gn/mon
# Define the path where the renamed files will be linked
outputPath: /home/jessica.liptak/test_input
# Define the target file(s) and variable name(s) to substitute in each file (1 variable per file)
files:
  -
     name: SAM0-UNICON_r1i1p1f1_gn.so.mon.nc
     var: siconc
     freq: *frequency
  -
    name: SAM0-UNICON_r1i1p1f1_gn.tas.mon.nc
    var: prect
    freq: *frequency
