version: 2

checkout:
  post:
    - ./ci-support/checkout_merge_commit.sh
        
aliases:

  - &setup_miniconda
    name: setup_miniconda
    command: |
      mkdir -p workspace
      git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
      ls workspace/cdat
      # following will install miniconda3 under $WORKDIR/miniconda/bin
      python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py2.7'
      
  - &create_conda_env
    name: create_conda_env
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       conda config --set always_yes yes --set changeps1 no
       conda update -y -q conda
       conda config --set anaconda_upload no
       conda create -q -n py2 -c cdat/label/nightly -c pcmdi/label/nightly -c conda-forge -c cdat lazy-object-proxy cmor python=2.7 testsrunner

  - &setup_cmor
    name: setup_cmor
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       set +e
       source activate py2
       echo "ACTIVATE RETURN CODE $?"
       set -e
       git clone https://github.com/PCMDI/cmor
       exit 0

  - &run_prepare_tests
    name: run_prepare_tests
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export UVCDAT_ANONYMOUS_LOG=False
       set +e
       source activate py2
       set -e
       cp Tables/* cmor/Tables
       cd cmor
       python run_tests.py -v2 -H -n1 Test/test_python_CMIP6_CV*.py

jobs:
  macos_cmip6:
    macos:
      xcode: "9.2.0"
    environment:
      WORKDIR: "workspace/test_macos_cmor"
      UVCDAT_ANONYMOUS_LOG: "False"
      OS: "osx-64"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *setup_cmor
      - run: *run_prepare_tests

  linux_cmip6:
    machine:
      image: circleci/classic:latest
    environment:
      WORKDIR: "workspace/test_linux_cmor"
      UVCDAT_ANONYMOUS_LOG: "False"
      OS: "linux-64"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *setup_cmor
      - run: *run_prepare_tests

workflows:
  version: 2
  nightly:
    jobs:
      - macos_cmip6
      - linux_cmip6
