## Sample configuration file for configuring environment settings
## PODs to run, and case/ensemble names and attributes

# POD(s) to run with ensemble case members
pod_list:
  name :
    -  "example"
# case names (a.k.a. ensemble members)
case_list :
  name :
   - "case_name_01"
   - "case_name_02"
# define attributes for each case in blocks that match the case names
case_name_01 :
  FIRSTYR : "YYYY"
  LASTYR : "YYYY"
  model : "model_name"
  convention: "CESM|CMIP|GFDL"

case_name_02 :
  FIRSTYR : "YYYY"
  LASTYR : "YYYY"
  model : "model_name"
  convention: "CESM|CMIP|GFDL"

environment_paths :
  # Parent directory containing observational data used by individual PODs.
  OBS_DATA_ROOT : "../inputdata/obs_data"
  # Parent directory containing results from different models.
  MODEL_DATA_ROOT : "../mdtf_test_data"
  # Working directory.
  WORKING_DIR : "../wkdir"
  # Directory to write output. The results of each run of the framework will be
  # put in a subdirectory of this directory. Defaults to WORKING_DIR if blank.
  OUTPUT_DIR : "../wkdir"
  # Location of the Anaconda/miniconda installation to use for managing
  # dependencies (path returned by running `conda info --base`.) If empty,
  # framework will attempt to determine location of system's conda installation.
  conda_root : "~/miniconda3"
  # Directory containing the framework-specific conda environments. This should
  # be equal to the "--env_dir" flag passed to conda_env_setup.sh. If left
  # blank, the framework will look for its environments in the system default location.
  conda_env_root : "~/miniconda3/envs"
  ## OPTIONAL SETTINGS ------------------------------------------------------------------
  # Any command-line option recognized by the mdtf script (type `mdtf --help`)
  # can be set here, in the form "flag name": "desired setting".
optional_settings :
  # Method used to fetch model data.
  data_manager : "Local_File"
  #  Method used to manage dependencies.
  environment_manager: "Conda"
  ## Settings affecting what output is generated:
  # Set to true to have PODs save postscript figures in addition to bitmaps.
  save_ps: false
  # Set to true to have PODs save netCDF files of processed data.
  save_nc: false
  # Set to true to save HTML and bitmap plots in a .tar file.
  make_variab_tar : false
  # Set to true to overwrite results in OUTPUT_DIR; otherwise results saved  under a unique name.
  overwrite: false
  ## Settings used in debugging:
  # Log verbosity level.
  verbose: 1
  # Set to true for framework test. Data is fetched but PODs are not run.
  test_mode : false
  # Set to true for framework test. No external commands are run and no remote
  # data is copied. Implies test_mode.
  dry_run: false

