# This file builds and runs a lightweight version of the MDTF test suite.
# Note that the tests assess functionality of the diagnostics,
# and do not evaluate data or scientific content.
name: MDTF_test

on:
  push:
    branches:
      - add_albedo_fb_to_ci
  pull_request:
    branches:
      - add_albedo_fb_to_ci
defaults:
  run:
    shell: bash -l {0}
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        conda-root: [/usr/share/miniconda3, /Users/runner/miniconda3]
        json-file-set3: ["tests/github_actions_test_ubuntu_set3.jsonc", "tests/github_actions_test_macos_set3.jsonc"]
        # if experimental is true, other jobs to run if one fails
        experimental: [false]
        exclude:
          - os: ubuntu-latest
            conda-root: /Users/runner/miniconda3
          - os: ubuntu-latest
            json-file-set3: "tests/github_actions_test_macos_set3.jsonc"
          - os: macos-latest
            conda-root: /usr/share/miniconda3
          - os: macos-latest
            json-file-set3: "tests/github_actions_test_ubuntu_set3.jsonc"
          - conda-root: /usr/share/miniconda3
            json-file-set3: "tests/github_actions_test_macos_set3.jsonc"
          - conda-root: /Users/runner/minconda3
            json-file-set3: "tests/github_actions_test_ubuntu_set3.jsonc"
      max-parallel: 2
    steps:
    - uses: actions/checkout@v2
    - name: Download Miniconda 3
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: 3.7
        mamba-version: "*"
        channels: conda-forge,defaults
    - name: Verify miniconda
      run: |
        conda info -a
    - name: Install XQuartz if macOS
      if: ${{ matrix.os == 'macos-latest' && matrix.conda-root == '/Users/runner/miniconda3' }}
      run: |
        echo "Installing XQuartz"
        brew install --cask xquartz
    - name: Set environment variables
      run: |
        echo "POD_OUTPUT=$(echo $PWD/../wkdir/GFDL.Synthetic)" >> $GITHUB_ENV
    - name: Install Conda Environments
      run: |
        echo "Installing Conda Environments"
        # MDTF-specific setup: install all conda envs
        ./src/conda/conda_env_setup.sh --all --conda_root ${{matrix.conda-root}}
        # create the synthetic data environment
        echo "Creating the _MDTF_synthetic_data environment"
        mamba env create --force -q -f ./src/conda/_env_synthetic_data.yml
    - name: Generate Model Data
      run: |
        cd ../
        conda activate _MDTF_synthetic_data
        pip install mdtf-test-data
        mkdir mdtf_test_data ; cd mdtf_test_data
        # generate the data and run unit tests
        mdtf_synthetic.py -c CMIP --startyear 1990 --nyears 20
        cd ../
        mkdir wkdir

    - name: Get observational data for set 3
      run: |
        echo "${PWD}"
        # remove data from previous run
        # Actions moves you to the root repo directory in every step, so need to cd again
        cd ../inputdata/obs_data
        echo "deleting obs data from set 2"
        rm -rf *
        cd ../../
        echo "Available Space"
        df -h
        # attempt FTP data fetch
        # allow 20 min for transfer before timeout; Github actions allows 6 hours for individual
        # jobs, but we don't want to max out resources that are shared by the NOAA-GFDL repos.
       
        curl --verbose --ipv4 --connect-timeout 8 --max-time 1200 --retry 128 --ftp-ssl --ftp-pasv -u "anonymous:anonymous" ftp://ftp.gfdl.noaa.gov/perm/oar.gfdl.mdtf/albedofb_obs_data.tar --output albedofb_obs_data.tar
        echo "Untarring set 3 CMIP standard test files"
        tar -xvf albedofb_obs_data.tar
        # clean up tarballs
        rm -f *.tar
        rm -f *.tar.gz
    - uses: pCYSl5EDgo/cat@master
      id: cat
      with:
        path: wkdir/CMIP_Synthetic_r1i1p1f1_gr1_19900101-20091231/albedofb/albedofb.log
    - name: Run diagnostic tests set 3
      continue-on-error: true
      run: |
        conda activate _MDTF_base
        # run the test PODs
        echo "${CWD}"
        ./mdtf -v -f ${{matrix.json-file-set3}}
        echo $TEXT
      env:
        TEXT: ${{ steps.cat.outputs.albedofb.log }}
