# This file builds and runs a lightweight version of the MDTF test suite.
# Note that the tests assess functionality of the diagnostics,
# and do not evaluate data or scientific content.
name: test_cmip

on:
  push:
    branches:
      - add_temp_extremes_distshape_to_CI
  pull_request:
    branches:
      - add_temp_extremes_distshape_to_CI
defaults:
  run:
    shell: bash -l {0}
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        conda-root: [/usr/share/miniconda3, /Users/runner/miniconda3]
        json-file-set3: ["tests/github_actions_test_ubuntu_set3.jsonc", "tests/github_actions_test_macos_set3.jsonc"]
        # if experimental is true, other jobs to run if one fails
        experimental: [false]
        exclude:
          - os: ubuntu-latest
            conda-root: /Users/runner/miniconda3
          - os: ubuntu-latest
            json-file-set3: "tests/github_actions_test_macos_set3.jsonc"
          - os: macos-latest
            conda-root: /usr/share/miniconda3
          - os: macos-latest
            json-file-set3: "tests/github_actions_test_ubuntu_set3.jsonc"
          - conda-root: /usr/share/miniconda3
            json-file-set3: "tests/github_actions_test_macos_set3.jsonc"
          - conda-root: /Users/runner/minconda3
            json-file-set3: "tests/github_actions_test_ubuntu_set3.jsonc"
      max-parallel: 2
    steps:
    - uses: actions/checkout@v2
    - name: Download Miniconda 3
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: 3.8
    - name: Verify miniconda
      run: |
        conda info -a
    - name: Install XQuartz if macOS
      if: ${{ matrix.os == 'macos-latest' && matrix.conda-root == '/Users/runner/miniconda3' }}
      run: |
        echo "Installing XQuartz"
        brew install --cask xquartz
    - name: Set environment variables
      run: |
        echo "POD_OUTPUT=$(echo $PWD/../wkdir/GFDL.Synthetic)" >> $GITHUB_ENV
    - name: Install Conda Environments
      run: |
        # create the synthetic data environment
        echo "Creating the _MDTF_synthetic_data environment"
        conda env create --force -q -f ./src/conda/_env_synthetic_data.yml
        # install mamba (https://github.com/mamba-org/mamba) for faster dependency resolution
        echo "Installing Mamba"
        conda install mamba -n base -c conda-forge
        echo "Installing Conda Environments"
        # MDTF-specific setup: install all conda envs
        ./src/conda/conda_env_setup.sh --all --mamba --conda_root ${{matrix.conda-root}}
    - name: Generate Model Data
      run: |
        cd ../
        conda activate _MDTF_synthetic_data
        pip install mdtf-test-data
        mkdir mdtf_test_data ; cd mdtf_test_data
        # generate the data and run unit tests
        mdtf_synthetic.py -c CMIP --startyear 1 --nyears 10 --unittest
        cd ../
        echo ${PWD}
        ls */*
    - name: Get observational data for set 3
      run: |
        echo "${PWD}"
        cd ../
        echo "Available Space"
        df -h
        # attempt FTP data fetch
        # allow 20 min for transfer before timeout; Github actions allows 6 hours for individual
        # jobs, but we don't want to max out resources that are shared by the NOAA-GFDL repos.
        curl --verbose --ipv4 --connect-timeout 8 --max-time 1200 --retry 128 --ftp-ssl --disable-epsv --ftp-pasv -u "anonymous:anonymous" ftp://ftp.gfdl.noaa.gov/perm/oar.gfdl.mdtf/temp_extremes_distshape_obs_data.tar --output temp_extremes_distshape_obs_data.tar
        ## make input data directories
        mkdir -p inputdata/obs_data
        echo "Untarring set 3 test files"
        tar -xvf temp_extremes_distshape_obs_data.tar
        # clean up tarballs
        rm -f *.tar
        mkdir wkdir
        echo ${PWD}
        ls ./inputdata/obs_data/*
    - name: Run diagnostic tests set 3
      run: |
        conda activate _MDTF_base
        cat ./mdtf
        # trivial check that install script worked
        ./mdtf --version
        # run the test PODs
        ./mdtf -v -f ${{matrix.json-file-set3}}
    - name: Run unit tests
      run: |
        echo "${PWD}"
        conda activate _MDTF_base
        python -m unittest discover
